spring:
  datasource:
    password: asror
    username: asror
    url: jdbc:postgresql://localhost:5433/rspcm
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

otp:
  retry-wait-time: 60
  retry-count: 3
  time-to-live: 86400

notification:
  eskiz:
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

token:
  expiration: 86400
  token: nC1zvT1QWqD7jVqz9Z2Dq9cF4o3j1+gZB6gXx8Llx9A=

logging:
  level:
    root: WARN
